[general]
live_config_reload = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[font]
normal = { family = "HackNerdFont", style = "Regular" }

[window]
decorations = "None"
startup_mode = "Maximized"
